#!/bin/bash

# JankyBorders configuration
# Colors are in format 0xAARRGGBB (Alpha, Red, Green, Blue)

borders \
  active_color=0xffffffff \
  inactive_color=0x00000000 \
  width=2.0 \
  style=round \
  hidpi=on \
  ax_focus=on